# Generated by Django 5.0.1 on 2026-01-03 19:24

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OCRJob',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(max_length=500, upload_to='uploads/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'bmp', 'tiff', 'gif'])])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
            ],
            options={
                'verbose_name': 'OCR Job',
                'verbose_name_plural': 'OCR Jobs',
                'db_table': 'ocr_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='ocr_jobs_created_7b652b_idx'), models.Index(fields=['status', '-created_at'], name='ocr_jobs_status_c4132a_idx')],
            },
        ),
    ]
